FROM openjdk:11

RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -  && \
    apt-get -yy update && \
    apt-get install -y nodejs && \
    mkdir -p /code/node && \
    cd /code/node && \
    npm install pg

COPY synch_commit_test.js /code/node/synch_commit_test.js

CMD ["/bin/bash"]
