FROM openjdk:11

RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -  && \
    apt-get -yy update && \
    apt-get install -y nodejs && \
    mkdir -p /code/node && \
    mkdir -p /code/java && \
    cd /code/node && \
    npm install pg

COPY node/synch_commit_test.js /code/node/synch_commit_test.js

COPY java/dbcluster.properties /code/java/dbcluster.properties
COPY java/postgresql.jar /code/java/postgresql.jar
COPY java/DBCLusterTestWithConnectionPool.java /code/java/DBCLusterTestWithConnectionPool.java

RUN cd /code/java && \
	javac -cp postgresql.jar:. DBCLusterTestWithConnectionPool.java

CMD ["/bin/bash"]
